{% set name = "pyvmomi" %}
{% set version = "6.7.3" %}

 package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

 source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d639d09eb3c7b118bc83b48472c27a4567dcc128dac0ac25ee2c03ed6afbe584

 build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv "

 requirements:
  host:
    - pip
    - python
  run:
    - python
    - requests >=2.3.0
    - six >=1.7.3

 test:
  imports:
    - pyVim
    - pyVmomi

 about:
  home: https://github.com/vmware/pyvmomi
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: VMware vSphere Python SDK

 extra:
  recipe-maintainers:
    - pg-hbk
    - sy-hbk
