travis:
  secure:
    BINSTAR_TOKEN: VgV6SXgOpklUgsukHmoNj4LNNlAbKCuXSzw+T02P/gLdrrfVrpz1/j5U/Q0fu0+mIvWnLsU/K5wNte8k99WGU3g6UJbnAxMu2GA1lPa63EDfoLsLebh3jc9jdKZw8x+lHuG+pIB/gH9s5rQqTBbXXx2RMuf4LScqFLMdqNe4DLhDsUgVC95QwcNt19JPspWA65JdsURsGdqLtjiQFQildbsEMC8fbCgTNW0Kzoo2ai7wdYGisInb5BpBhlM/90dsdC+aTc8QCihsoi5cNz5rTlH7vQKJjazcJK8Aee4rih2FPCQttnbKRkGymTmPtROZ8T4JJ8IrXVK1tFlmEajJjUBx+ewop9T/8z82GgTWWmnHOHbRmLquYDg+Fpb7CvcF+TjmYbw+LSv0t9CtOoFfi8ehMsNOBrFeuIS95h/d3p5cROLUTP0S1K2zq815aKYNoMFyXCYf8KGUR7MSsx97zy9Hgye2/uB7cTGVxeBJ68R4gGrbyG8MBQRR0PqimmOB4ve7qHY71UjMoiCJAPT3ZvqcfpjPpq87/uMAIvCic+cBMK1c/UFhYyjp+X1luYio6Td8n6glxHlaSMQoiFdBqsBND5SCpvS8iC5HUowMyo87c8ePEFRq43qNp47KtKDUswUrRIEhyKGlTOHvCMN7cfMiXY+e2EQR5zC7kGtbRQY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
